concurrent = 4
check_interval = 0
log_level = "warning"

[session_server]
  session_timeout = 1800

[[runners]]
  name = "b92eea8143bc"
  url = "http://gitlab-ee.example.org/"
  token = "DaPRE5QQ48Q_N-H4eyG2"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    extra_hosts = ["gitlab-ee.example.org:10.254.249.89"]
    network_mode = "gitlab_net"


